# Default values for cyberlynx
replicaCount: 1

backend:
  image:
    repository: mnshchtri/cyber-lynx
    tag: latest # Jenkins will update this automatically
    pullPolicy: Always
  port: 8080

frontend:
  image:
    repository: mnshchtri/cyber-lynx
    tag: latest
    pullPolicy: Always
  port: 80

gateway:
  enabled: true
  name: cyberlynx-gateway # Specific override if needed, though templates will use fullname by default
  class: nginx

# Domains for HTTPRoutes
hostnames:
  app: "app.cyberlynx.citytech"
  grafana: "grafana.cyberlynx.citytech"
  argocd: "argocd.cyberlynx.citytech"

# Sensitive data (to be encoded in templates)
secrets:
  mongoUri: "bW9uZ29kYitzcnY6Ly9hZG1pbjpjeWJlcmx5bnhAY2x1c3RlcjAuYm4yYzF3bC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA=="
  jwtSecret: "c3VwZXJzZWNyZXRrZXkxMjM="
  geminiApiKey: "QUl6YVN5Qy1OekNDdV9yWmhQbTFiN0J4OTI1c3BncXVBMDBDRlZn"
