{{- if .Values.gateway.crossNamespaceRoutes.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "cyberlynx.fullname" . }}-argocd-route
  labels:
    {{- include "cyberlynx.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name | default "cyberlynx-gateway" }}
    namespace: {{ .Values.gateway.namespace | default "default" }}
  hostnames:
  - {{ .Values.hostnames.argocd | quote }}
  rules:
  - backendRefs:
    - name: argocd-server
      namespace: argocd
      port: 80
      kind: Service
{{- end }}
