apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | default "cyberlynx-gateway" }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "cyberlynx.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.class | default "nginx" }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
