apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cyberlynx.fullname" . }}-secrets
  labels:
    {{- include "cyberlynx.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}